# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 887d8f857efbab81e787ab4d264201bcac672125659a352abe46b422c2217910968fc37d63621b6500a42a718aad47bd9208f72a9f25ff39a6f255fabd20f9ed

test:
  secret_key_base: a8111603c883af75cca43942756dae17323c558a91aff9cd63bf0ae3fab852d44873b699e9ebeb9ca85ed79b2e80668fc7edda16bdaefe7ca063510189434120

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
